### ISSUE TITLE
unselectAll() : feature request to unselect all nodes

### ISSUE THREAD

**Issue by yuki** [jbtronics/bs-treeview#1]
- **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project

- **Summary**
The idea is to create a function "unselectAll()" to unselect all the nodes (as there are "collapseAll()", "expandAll()"..)

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
I have tried to create the next code around line 1259 in lib/BSTreeView.ts :

```typescript
    /**
     Unselects all tree nodes
     @param {optional Object} options
     */
    unselectAll(): this {
        this.unselectNode(this._tree);

        return this;
    }
```

But when I do ```npm build``` and then use the "build" directory into my project I obtain the error "main.ts:6 ERROR TypeError: this.tree_data.unselectAll is not a function".

I'm new coding with Typescript, and don't know how modules work, so sorry for not making a real pull-request with working code.

PS: Thanks for making this great library. I used the Jon Miles'  [bootstrap-treeview](https://github.com/jonmiles/bootstrap-treeview) and it's great to have an alternative in typescript.

**Comment by jbtronics** [comment]
This methods are now available with version 1.0.5
